[project]
name = "molmo-spaces-maniskill"
version = "0.0.1"
description = "ManiSkill environments for ProcTHOR and RoboTHOR"
readme = "README.md"
authors = []
requires-python = ">=3.11"
dependencies = [
    "mani-skill==3.0.1b1",
    "mujoco",
    "tyro",
    "msgspec",
    "setuptools>=83.0.0",
    "molmospaces-resources==0.0.3a2",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pybind11-stubgen",
    "ruff",
    "ty",
    "ipython",
    "ipdb",
]

[tool.uv.sources]
mani-skill = { index = "robotics-folks" }

[[tool.uv.index]]
name = "robotics-folks"
url = "https://codeberg.org/api/packages/robotics-folks/pypi/simple/"
explicit = true

[project.scripts]
ms-download = "molmo_spaces_maniskill.downloader.main:main"

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # PEP8
    "W",
    # Pylint
    "PL",
]
ignore = [
    "C408", # dict() calls
    "C901", # function complexity
    "E501", # line too long (handled by line-length setting)
    "B006", # defaults shouldn't be mutable
    "UP015", # redundant mode arguments in open should be fine for now
    "SIM117", # allow nested with statements for now
    "SIM102", # don't be picky about nested if statements
    "SIM114", # don't be picky about merging if branches using or
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLC0415",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.environment]
extra-paths = ["./typings"]
