"""PickTaskSampler variant that scatters humanoid avatars (scene population /
soft obstacles) around the episode, placed via the same occupancy-map
machinery used for robot placement (env.get_thormap()).

Avatars are generated by scripts/assets/convert_rocketbox_avatars.py from the
Microsoft Rocketbox avatar library and registered as a local user asset
library (see that script's docstring for setup; not committed to the repo).
Two variants, selected by PickWithAvatarsTaskSamplerConfig.avatar_articulated:
articulated ragdolls (~20-body ball-joint chain, ASSETS_DIR/avatars_articulated,
default) or static mannequins (single free-jointed body, ASSETS_DIR/avatars).
Both ship exactly one top-level body per avatar MJCF, so staging/placement
below doesn't need to know which variant is in use.
"""

import json
import logging

import mujoco
import numpy as np
from mujoco import MjSpec

from molmo_spaces.env.env import CPUMujocoEnv
from molmo_spaces.molmo_spaces_constants import ASSETS_DIR, USER_ASSET_LIBRARIES
from molmo_spaces.tasks.pick_task import PickTask
from molmo_spaces.tasks.pick_task_sampler import PickTaskSampler
from molmo_spaces.tasks.task_sampler_errors import ObjectPlacementError
from molmo_spaces.utils.lazy_loading_utils import install_uid
from molmo_spaces.utils.mujoco_scene_utils import place_object_near

log = logging.getLogger(__name__)

_AVATAR_STAGING_CENTER = np.array([5.0, -5.0, 25.0])  # distinct from pickupables' [5, 5, 25]


def _avatar_library_name(articulated: bool) -> str:
    return "avatars_articulated" if articulated else "avatars"


def _ensure_avatar_library_registered(library_name: str) -> None:
    if library_name in USER_ASSET_LIBRARIES:
        return
    avatars_dir = ASSETS_DIR / library_name
    if not (avatars_dir / "assets_index.json").exists():
        raise RuntimeError(
            f"No avatar assets found at {avatars_dir}. Generate them first with "
            f"scripts/assets/convert_rocketbox_avatars.py "
            f"{'articulate' if library_name == 'avatars_articulated' else 'convert'} --all "
            "(see its docstring for setup)."
        )
    from molmo_spaces.molmo_spaces_constants import register_user_asset_library

    register_user_asset_library(library_name, avatars_dir)


def _discover_avatar_uids(library_name: str) -> list[str]:
    index_path = ASSETS_DIR / library_name / "assets_index.json"
    return sorted(json.loads(index_path.read_text()).keys())


class PickWithAvatarsTaskSampler(PickTaskSampler):
    def __init__(self, config):
        self._avatar_library_name = _avatar_library_name(
            config.task_sampler_config.avatar_articulated
        )
        _ensure_avatar_library_registered(self._avatar_library_name)
        super().__init__(config)
        self._avatar_names: list[str] = []

    def add_auxiliary_objects(self, spec: MjSpec) -> None:
        super().add_auxiliary_objects(spec)
        self._add_avatars_to_scene(spec)

    def _add_avatars_to_scene(self, spec: MjSpec) -> None:
        task_sampler_config = self.config.task_sampler_config
        pool = task_sampler_config.avatar_uids or _discover_avatar_uids(self._avatar_library_name)
        if not pool:
            raise ValueError("No avatar UIDs available (pool is empty)")

        num_avatars = task_sampler_config.num_avatars
        replace = len(pool) < num_avatars
        selected_uids = list(np.random.choice(pool, size=num_avatars, replace=replace))

        self._avatar_names = []
        for i, uid in enumerate(selected_uids):
            avatar_xml = install_uid(uid)
            avatar_spec = MjSpec.from_file(str(avatar_xml))
            if len(avatar_spec.worldbody.bodies) != 1:
                log.warning(
                    f"{avatar_xml} has {len(avatar_spec.worldbody.bodies)} bodies, expected 1."
                )
            avatar_body = avatar_spec.worldbody.bodies[0]

            # Stage off-scene in a grid, same pattern as PickTaskSampler's own
            # added-pickupables staging (_add_pickupables_to_scene) but at a
            # distinct location so the two staging areas don't overlap. No
            # reorientation quat here (unlike pickupables' own +90deg-about-X,
            # which corrects for Objaverse's axis convention) -- avatars are
            # already authored Z-up, standing, by convert_rocketbox_avatars.py.
            position = _AVATAR_STAGING_CENTER + np.array([i, 0.0, 0.0])
            attach_frame = spec.worldbody.add_frame(pos=position)
            # Namespace must match the "{idx}_{idx}" two-part pattern
            # PickTaskSampler._get_scene_objects (pick_task_sampler.py) uses to
            # recognize and skip already-added objects when scanning for pickup
            # candidates -- same convention _add_pickupables_to_scene uses
            # (f"{namespace}{i}_{j}/"), just with a fixed second index since
            # avatars have no multiplier dimension.
            namespace = f"{task_sampler_config.avatar_namespace}{i}_0/"
            original_body_name = avatar_body.name
            attach_frame.attach_body(avatar_body, namespace, "")

            self._avatar_names.append(namespace + original_body_name)

        log.info(f"Added {len(self._avatar_names)} avatars to scene: {selected_uids}")

    def _sample_task(self, env: CPUMujocoEnv) -> PickTask:
        task = super()._sample_task(env)
        self._place_avatars(env)
        return task

    def _place_avatars(self, env: CPUMujocoEnv) -> None:
        if not self._avatar_names:
            return

        task_sampler_config = self.config.task_sampler_config
        om = env.object_managers[env.current_batch_index]
        data = env.current_data

        thormap = env.get_thormap(agent_radius=task_sampler_config.avatar_agent_radius)
        free_points = thormap.get_free_points()[:, :2]

        robot_xy = env.current_robot.robot_view.base.pose[:2, 3]
        pickup_obj_name = self.config.task_config.pickup_obj_name
        pickup_xy = om.get_object(pickup_obj_name).position[:2]
        exclude_xy = [robot_xy, pickup_xy]

        min_spacing = task_sampler_config.avatar_min_spacing
        rng = np.random.default_rng()
        shuffled = free_points[rng.permutation(len(free_points))]

        # A candidate that's spatially "free" per the dilated occupancy map can still
        # fail place_object_near's real contact check (the map dilation is an
        # approximation, not an exact clearance guarantee) -- so each avatar gets its
        # own retry budget across *different* candidates, and `next_idx` advances
        # monotonically across avatars so a point already tried (successfully or not)
        # is never reconsidered for a later avatar.
        accepted_points: list[np.ndarray] = []
        next_idx = 0
        placed = 0
        for name in self._avatar_names:
            avatar_id = om.get_object_body_id(name)
            attempts = 0
            placed_this_avatar = False
            while attempts < task_sampler_config.max_avatar_point_attempts and next_idx < len(
                shuffled
            ):
                candidate = shuffled[next_idx]
                next_idx += 1
                too_close = any(
                    np.linalg.norm(candidate - other) < min_spacing
                    for other in accepted_points + exclude_xy
                )
                if too_close:
                    continue
                attempts += 1
                point_3d = np.array([candidate[0], candidate[1], 0.02])
                try:
                    place_object_near(
                        data=data,
                        object_id=avatar_id,
                        placement_point=point_3d,
                        min_dist=0.0,
                        max_dist=task_sampler_config.avatar_placement_radius,
                    )
                except (ObjectPlacementError, ValueError):
                    continue
                accepted_points.append(candidate)
                placed += 1
                placed_this_avatar = True
                break

            if not placed_this_avatar:
                log.info(f"[Avatars] Could not place {name} after {attempts} attempts")

        mujoco.mj_forward(env.current_model, data)
        log.info(f"[Avatars] Placed {placed}/{len(self._avatar_names)} avatars")
